config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'about', to: 'about#index'

  #========User Routes ==================#
  get 'signup', to: 'users#new'
  resources :users, except:[:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles
  resources :posts
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_posts
  has_many :posts, through: :category_posts
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  validates_uniqueness_of :name
  

end

app/models/category_post.rb
      class CategoryPost < ApplicationRecord

        belongs_to :category
        belongs_to :post

      end

app/models/post.rb
class Post < ApplicationRecord
  has_many :category_posts
  has_many :categories, through: :category_posts
  belongs_to :user
  validates :title, :body,  presence: true, length: {minimum: 3}
  validates :user_id , presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  before_save { self.email = email.downcase}

  validates :username,
              presence: true,
              uniqueness: {case_sensitive: false},
              length: {minimum: 3, maximum: 25}

    VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email,
              presence: true,
              uniqueness: {case_sensitive: false},
              format: {with: VALID_EMAIL_REGEX}

  has_secure_password

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

    def index
        
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "you need to be logged in"
      redirect_to root_path
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category
  before_action :require_admin, only: [:new, :edit]



  def index
    @categories = Category.paginate(page: params[:page], per_page: 8)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category has been created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update

  end

  def show

  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "You are not permited to this action"
      redirect_to root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        redirect_to posts_path if logged_in?
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show, :destroy, :update]
  before_action :require_user , except: [:index, :show]
  before_action :require_same_user , except: [:index, :show, :new, :create, :update]


 def index
   @posts = Post.paginate(page: params[:page], per_page: 2).order('id DESC')
 end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    #render plain: params[:post].pretty_inspect
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "Your post has been created"
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post is getting updated"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def show
  end

 def destroy
   flash[:danger] = "Post has been deleted"
   @post.destroy
   redirect_to posts_path
 end

  private
 def set_post
   @post = Post.find(params[:id])
 end
  def post_params
    params.require(:post).permit(:title, :body, category_ids:[])
  end
  def require_same_user
    if current_user != @post.user and !current_user.admin?
      flash[:warning] = "You don't have access to this page"
      redirect_to root_path
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "Somethig went wrong, try again"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  before_action :require_same_user, only: [:show ]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Congrats!, you has been signed up successfully'
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit

  end

  def update

  end

  def show

  end

  def destroy

  end

  private
  def user_params
    params.require(:user).permit(:username, :email.downcase, :password)
  end
  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:warning] = 'You do not allowed to access others data'
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, size )
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, class: "m-4 rounded-circle")
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/about/index.html.erb
    <h2> THis is the about page</h2>

    <%= link_to "Back TO Home", root_path %>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/categories/_category.html.erb
<span>
   <%= link_to category.name, category_path(category) %>
  &nbsp;
</span>

app/views/categories/index.html.erb
<div class="container">

<h2 align="center">Listing Categories</h2>
<div class="justify-content-center">
  <div class="row">
  <% @categories.each do |category| %>


    <h3 class="jumbotron col  ml-3">

      <%= link_to category.name, category_path(category) %>

    </h3>



<% end %>
  </div>
  <div  align="center">
    <%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class:  "pagination-sm") %>
  </div>

</div>
</div>

app/views/categories/new.html.erb
<div class="errors" style="padding: 50px">
  <%= render 'shared/errors', object: @category %>
</div>

<div class="offset-md-2">
  <%= form_for @category do |f| %>
    <div class="form-group row">
      <%= f.label :name, class:'col-form-label col-1'%>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "name goes here...  " %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-1"></div>
      <div class="col-8">
        <%= f.submit  class: "btn btn-primary btn-block"%>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="col">
    <h3 align="center"> <%= @category.name %> </h3>
    <hr>
  <%= render @category.posts , object: @category.posts %>
</div>
</div>

app/views/home/index.html.erb
<div class="intro col-12 text-center">
  <div class="intro-data">
    <h1> Welcome to Rails Blog</h1>
    <%= link_to "Sign Up Now", signup_path   , class: "btn btn-secondary btn-lg" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="col-md-8 col-xs-12 col-sm-12 text-center" style="padding: 20px">
    <span class="text-muted">All Rights Reserved &commat; 2018 | <strong>Mahmoud Abdelmoneim</strong> </span>
    </div>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="col-sm-8" style="margin: 0 auto">
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
      <strong> <%= name %> </strong> <%= msg %>.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Rails Blog", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Posts", posts_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions <%= "(Admin)" if current_user.admin? %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <%= link_to "New Post", new_post_path, class: "dropdown-item" %>
          <%= link_to "Your Profile", user_path(current_user), class: "dropdown-item" %>
        </div>
      </li>
        <% end %>

      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">

            <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
            <% Category.all.each do |category| %>
            <%= link_to category.name , category_path(category), class: "dropdown-item" %>
            <%end %>
            <div class="dropdown-divider"></div>
            <%= link_to "create new category", new_category_path, class: "dropdown-item" %>

          </div>
        </li>
      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

    <ul class="navbar-nav float-right ml-5">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "logout", logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
      <%= render 'layouts/messages' %>
      <%= yield %>

  <%= render 'layouts/footer' %>

    <div class="debug m-3">
    <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<div class="errors" style="padding: 50px">
  <%= render 'shared/errors', object: @post %>
</div>
<div class="offset-md-2">
  <%= form_for @post do |f| %>
    <div class="form-group row">
      <%= f.label :title, class: 'col-form-label col-1' %>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "title goes here...  " %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :body, class: "col-from-label col-1" %>
      <div class="col-sm-8">
        <%= f.text_area :body, class: "form-control", rows: "6", placeholder: "Description for your post" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="offset-md-1 col-sm-8">
        <%= f.collection_check_boxes :category_ids, Category.all, :id , :name do |ch|  %>
          <%= ch.label(class: "checkbox-inline") {ch.check_box(class:"checkbox") + ch.text} %>
        <%end %>
      </div>
    </div>


    <div class="form-group row">
      <div class="col-1"></div>
      <div class="col-8">
        <%= f.submit class: "btn btn-primary btn-block" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<% object.each do |post| %>
  <div class="post jumbotron">
    <div class="post-title">
      <a href="<%= post_path(post) %>"><h2><%= post.title %></h2></a>
      <div class="post-meta-data">
        <small><%= time_ago_in_words(post.created_at)%> ago, by
          <%=  post.user.username.upcase_first  if post.user %>
        </small>
      </div>
    </div>
    <div>
      <p> <%=  truncate(post.body, length: 100) %> </p>
    </div>
    <% if logged_in? && (post.user == current_user || current_user.admin?) %>
    <div class="post-actions">
      <%= link_to "Edit", edit_post_path(post), class: "btn btn-success btn-sm" %>
      <%= link_to "delete", post_path(post), method: :delete, data: {confirm: "Are you really want to delete this post?"},
                  class: "btn btn-danger btn-sm" %>
    </div>
      <% end %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<div class="container">
<h2 align="center">Edit Post</h2>

<%= render 'form' %>
<div class="text-center">
[ <%= link_to "Cancel Editing and Back to Posts", posts_path%> ]
</div>
</div>

app/views/posts/index.html.erb
<h2 align="center">Lastest Posts </h2>
<div class="container">

<div class="mt-5"></div>


<%= render 'post', object: @posts %>

  <div class="col-sm-12" >
    <%= will_paginate(@posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class:  "pagination-sm offset-4") %>
  </div>

</div>

app/views/posts/new.html.erb
<h2 align="center">Create a new Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="post">
  <div class="col-lg-8 col-sm-12" style="margin: 0 auto">
<h2 class="jumbotron">
<%= @post.title %>
  <% if logged_in? && (@post.user == current_user || current_user.admin?) %>
  <div class="post-actions">
    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-success btn-sm" %>
    <%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "Are you really want to delete this post?"},
                class: "btn btn-danger btn-sm" %>
    <%= link_to "Back to Posts", posts_path, class: "btn btn-secondary btn-sm" %>
  </div>
    <% end %>
</h2>

<div class="post-body" align="left">
  <%= @post.body %>
</div>
    <hr>
    <% if @post.categories.any? %>
      <div class="post-cats" align="left">
        Related to:  <%= render @post.categories %>
      </div>


  <% end %>

  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="col-sm-8 alert alert-danger" style="margin: 0 auto" role="alert">
    <h4 class="alert-heading">
      <%= pluralize(object.errors.count, "error") %>
      Prevented Post form Being Published:
    </h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="errors" style="padding: 50px">
  <%= render 'shared/errors', object: @user %>
</div>

<h2 align="center"> Signup For RailS Blog</h2>

<div class="offset-md-2">
  <%= form_for @user do |f| %>
    <div class="form-group row">
      <%= f.label :username, class: 'col-form-label col-1' %>
      <div class="col-sm-8">
        <%= f.text_field :username, class: "form-control",
                         placeholder: "Enter your username...  " %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :email, class: "col-from-label col-1" %>
      <div class="col-sm-8">
        <%= f.email_field :email, class: "form-control",
                          placeholder: "Enter you E-mail" %>
      </div>
    </div>

      <div class="form-group row">
        <%= f.label :password, class: "col-from-label col-1" %>

        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control",
                               placeholder: "Enter you E-mail" %>
        </div>

      </div>

      <div class="form-group row">
        <div class="col-1"></div>
        <div class="col-8">
          <%= f.submit 'Signup',  class: "btn btn-primary btn-block" %>
        </div>
      </div>
  <% end %>
  </div>

app/views/users/show.html.erb
<div class="container">
  <div class="heading">
    <h1 align="center">My Profile</h1>
  </div>
  <div class="row">
    <div class="col-12" align="center">
      <%= gravatar_for @user, 250 %>
      <h3> <%= @user.username.upcase %></h3>
      <h3> <%= @user.email.downcase %></h3>
    </div>
  </div>
  <hr>
  <div class="mt-3">

    <strong><%= @user.username.upcase %>'s Posts </strong>
    <% if @user.posts.count > 0   %>
      <%= render 'posts/post', object: @user.posts %>
    <% else %>
      <p class=" text-center alert alert-secondary">You don't have any posts yet</p>
    <% end %>
  </div>

</div>